services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - observability

  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   restart: unless-stopped
  #   volumes:
  #     - '/:/host:ro,rslave'
  #   ports:
  #     - 9100:9100

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      - observability

  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisionning:/etc/grafana/provisionning
    depends_on:
      - prometheus
    networks:
      - observability

networks:
  observability: